### ISSUE TITLE
pip install -v -e .报错   Removed pypdfium2>=4.18.0 from https://files.pythonhosted.org/packages/7b/d1/d05fad9041c3f1e31dcb53f0bbb4d41ffec99b8b4d523ac527b6b908e4ed/pypdfium2-4.25.0.tar.gz#sha256=1691bfa3e65bc84fd8b1d26a6d68af90f9662771a647dd6c4e031d81c4a72037 (from pdfplumber->py-data-juicer==0.1.2) from build tracker '/tmp/pip-req-tracker-7jhdlfu7'

### ISSUE THREAD

**Issue by THUchenzhou** [alibaba/data-juicer#164]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

您好，我执行pip install -v -e .报错，请问有好的解决方法吗
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/anaconda3/bin/python /home/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp07_kb6wc Check the logs for full command output.
Removed pypdfium2>=4.18.0 from https://files.pythonhosted.org/packages/7b/d1/d05fad9041c3f1e31dcb53f0bbb4d41ffec99b8b4d523ac527b6b908e4ed/pypdfium2-4.25.0.tar.gz#sha256=1691bfa3e65bc84fd8b1d26a6d68af90f9662771a647dd6c4e031d81c4a72037 (from pdfplumber->py-data-juicer==0.1.2) from build tracker '/tmp/pip-req-tracker-7jhdlfu7'
Removed build tracker: '/tmp/pip-req-tracker-7jhdlfu7'

**Comment by zhijianma** [comment]
您好，感谢使用Data-Juicer。
您遇到的问题，我们暂时无法复现，建议您可以尝试下：

- 手从安装 pdfplumber 
 ```shell
   pip install pdfplumber
 ```
- 查看 tmp 所在目录是否硬盘空间不足
